version: '3'
volumes:
  influx_data: {}
  grafana_data: {}
services:
  influxdb:
    image: influxdb:alpine
    volumes:
      - influx_data:/var/lib/influxdb
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:5.1.5
    volumes: 
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    ports:
      - "3000:3000"